In [16]:
import pandas as pd

df = pd.read_csv('Quantified_dirty_churn.csv')

In [17]:
columns = ['Tenure_Months', 'Age', 'Gender', 'Contract_Type', 'Monthly_Charges', 'Total_Charges',
           'Internet_Service', 'Has_Multiple_Lines', 'Streaming_TV', 'Churn', 'Reason_for_Churn']
quant_df = pd.DataFrame(df, columns=columns)

In [ ]:
churn_df = quant_df[quant_df['Monthly_Charges'] <= quant_df['Total_Charges']]

calc_tenure = churn_df['Total_Charges'] / churn_df['Monthly_Charges']
churn_df['Tenure_Months'] = churn_df['Tenure_Months'].fillna(
    calc_tenure.round())

In [53]:
age_median = churn_df['Age'].median()
churn_df['Age'] = churn_df['Age'].replace(0.0, age_median)

In [30]:
churn_df['Gender'] = churn_df['Gender'].fillna(2)

In [44]:
churn_df = churn_df.dropna(subset=['Churn'])

In [54]:
churn_df.tail()

,Tenure_Months,Age,Gender,Contract_Type,Monthly_Charges,Total_Charges,Internet_Service,Has_Multiple_Lines,Streaming_TV,Churn,Reason_for_Churn
10094,51.0,48,1.0,3.0,89.72,4592.15,1.0,1.0,1.0,0.0,0
10095,6.0,42,0.0,1.0,55.60,335.77,2.0,0.0,0.0,0.0,0
10096,40.0,26,0.0,3.0,90.06,3604.38,1.0,1.0,1.0,1.0,1
10098,8.0,42,1.0,1.0,18.00,53.58,3.0,0.0,0.0,0.0,0
10099,54.0,20,0.0,2.0,36.72,828.14,3.0,0.0,0.0,0.0,0

In [56]:
churn_df.corr()

,Tenure_Months,Age,Gender,Contract_Type,Monthly_Charges,Total_Charges,Internet_Service,Has_Multiple_Lines,Streaming_TV,Churn,Reason_for_Churn
Tenure_Months,1.000000,-0.002453,0.021054,0.582064,-0.009722,0.085934,-0.017152,0.004161,0.012423,-0.323049,-0.235056
Age,-0.002453,1.000000,-0.017527,-0.006616,-0.005602,-0.002315,0.009577,0.011025,0.009441,0.007093,0.008317
Gender,0.021054,-0.017527,1.000000,0.012730,0.013484,0.010861,0.009513,0.010361,-0.001881,-0.007866,-0.020025
Contract_Type,0.582064,-0.006616,0.012730,1.000000,-0.005983,0.044930,-0.009157,0.007002,0.001077,-0.354867,-0.254529
Monthly_Charges,-0.009722,-0.005602,0.013484,-0.005983,1.000000,0.799416,-0.021089,0.007195,-0.007999,0.009910,-0.000972
Total_Charges,0.085934,-0.002315,0.010861,0.044930,0.799416,1.000000,-0.020836,0.009372,-0.004572,-0.023810,-0.016229
Internet_Service,-0.017152,0.009577,0.009513,-0.009157,-0.021089,-0.020836,1.000000,-0.006387,-0.312947,-0.101675,-0.067505
Has_Multiple_Lines,0.004161,0.011025,0.010361,0.007002,0.007195,0.009372,-0.006387,1.000000,0.002941,0.032226,0.021024
Streaming_TV,0.012423,0.009441,-0.001881,0.001077,-0.007999,-0.004572,-0.312947,0.002941,1.000000,0.042348,0.018373
Churn,-0.323049,0.007093,-0.007866,-0.354867,0.009910,-0.023810,-0.101675,0.032226,0.042348,1.000000,0.722362
Reason_for_Churn,-0.235056,0.008317,-0.020025,-0.254529,-0.000972,-0.016229,-0.067505,0.021024,0.018373,0.722362,1.000000

In [57]:
churn_df.isna().sum()

Tenure_Months          0
Age                    0
Gender                 0
Contract_Type         85
Monthly_Charges        0
Total_Charges          0
Internet_Service      70
Has_Multiple_Lines    44
Streaming_TV          82
Churn                  0
Reason_for_Churn       0
dtype: int64