In [115]:
import pandas as pd
import numpy as np

df = pd.read_csv("customer_churn_dirty (1).csv")

In [116]:
columns = ['Customer_ID', 'Tenure_Months', 'Age', 'Gender', 'Contract_Type', 'Monthly_Charges', 'Total_Charges',
           'Payment_Method', 'Internet_Service', 'Has_Multiple_Lines', 'Streaming_TV', 'Churn', 'Reason_for_Churn']
df = pd.DataFrame(df, columns=columns)

In [117]:
churn_df = df.drop(columns=['Payment_Method', 'Customer_ID'])

In [118]:
churn_df['Gender'] = churn_df['Gender'].str.strip().str.lower()

churn_df['Gender'] = churn_df['Gender'].replace(['male', 'm'], 1)
churn_df['Gender'] = churn_df['Gender'].replace(['female', 'f'], 0)
churn_df['Gender'] = churn_df['Gender'].replace(['n/a', 'other'], 2)

churn_df['Gender'] = pd.to_numeric(
    churn_df['Gender'], errors='coerce')

In [119]:
churn_df['Contract_Type'] = churn_df['Contract_Type'].str.strip().str.lower()

churn_df['Contract_Type'] = churn_df['Contract_Type'].replace(
    ['monthly', 'm', 'monthy'], 1)
churn_df['Contract_Type'] = churn_df['Contract_Type'].replace([
                                                              'yearly', 'y'], 2)
churn_df['Contract_Type'] = churn_df['Contract_Type'].replace(
    ['two-year', '2-year', 'two year'], 3)

churn_df['Contract_Type'] = pd.to_numeric(
    churn_df['Contract_Type'], errors='coerce').astype(float)

In [120]:
churn_df['Tenure_Months'] = churn_df['Tenure_Months'].abs()

In [121]:
churn_df['Monthly_Charges'] = pd.to_numeric(
    churn_df['Monthly_Charges'], errors='coerce')
churn_df['Monthly_Charges'] = churn_df['Monthly_Charges'].replace(
    r'[^\d.]', '', regex=True)

In [122]:
churn_df['Age'] = pd.to_numeric(churn_df['Age'], errors='coerce')

median_age = churn_df['Age'].median()
churn_df['Age'] = churn_df['Age'].fillna(median_age)
churn_df['Age'] = churn_df['Age'].astype(int)

In [123]:
churn_df['Total_Charges'] = pd.to_numeric(
    churn_df['Total_Charges'], errors='coerce')
missing_total_value = churn_df['Tenure_Months'] * churn_df['Monthly_Charges']

churn_df['Total_Charges'] = churn_df['Total_Charges'].fillna(
    missing_total_value)
churn_df['Total_Charges'] = churn_df['Total_Charges'].abs()

In [124]:
churn_df['Internet_Service'] = churn_df['Internet_Service'].str.strip().str.lower()

churn_df['Internet_Service'] = churn_df['Internet_Service'].replace(
    ['fiber', 'fiber optic'], 1)
churn_df['Internet_Service'] = churn_df['Internet_Service'].replace('dsl', 2)
churn_df['Internet_Service'] = churn_df['Internet_Service'].replace(
    ['no service', 'no', 'none', 'n'], 3)

In [125]:
churn_df['Has_Multiple_Lines'] = churn_df['Has_Multiple_Lines'].str.strip().str.lower()

churn_df['Has_Multiple_Lines'] = churn_df['Has_Multiple_Lines'].replace([
                                                                        'yes', 'y'], 1)
churn_df['Has_Multiple_Lines'] = churn_df['Has_Multiple_Lines'].replace([
                                                                        'no', 'n'], 0)


churn_df['Has_Multiple_Lines'] = pd.to_numeric(
    churn_df['Has_Multiple_Lines'], errors='coerce')

In [126]:
churn_df['Streaming_TV'] = churn_df['Streaming_TV'].str.strip().str.lower()

churn_df['Streaming_TV'] = churn_df['Streaming_TV'].replace(['yes', 'y'], 1)
churn_df['Streaming_TV'] = churn_df['Streaming_TV'].replace(['no', 'n'], 0)

churn_df['Streaming_TV'] = pd.to_numeric(
    churn_df['Streaming_TV'], errors='coerce').astype(float)

In [127]:
churn_df['Churn'] = churn_df['Churn'].str.strip().str.lower()

churn_df['Churn'] = churn_df['Churn'].replace(['yes', 'y'], 1)
churn_df['Churn'] = churn_df['Churn'].replace(['no', 'n'], 0)

churn_df['Churn'] = pd.to_numeric(
    churn_df['Churn'], errors='coerce')

In [ ]:
churn_df['Reason_for_Churn'] = churn_df.Reason_for_Churn.str.strip().str.lower()

churn_df['Reason_for_Churn'] = churn_df.Reason_for_Churn.fillna(0)
churn_df['Reason_for_Churn'] = churn_df.Reason_for_Churn.replace('price', 1)
churn_df['Reason_for_Churn'] = churn_df.Reason_for_Churn.replace(
    'poor service', 2)
churn_df['Reason_for_Churn'] = churn_df.Reason_for_Churn.replace(
    'competitor', 3)
churn_df['Reason_for_Churn'] = churn_df.Reason_for_Churn.replace('other', 4)

churn_df['Reason_for_Churn'] = pd.to_numeric(
    churn_df['Reason_for_Churn'], errors='coerce')

In [129]:
churn_df.head(40)

,Tenure_Months,Age,Gender,Contract_Type,Monthly_Charges,Total_Charges,Internet_Service,Has_Multiple_Lines,Streaming_TV,Churn,Reason_for_Churn
0,19.0,46,0.0,1.0,24.20,457.73,3,0.0,0.0,1.0,4
1,49.0,54,0.0,1.0,50.16,2469.71,NaN,0.0,0.0,0.0,4
2,19.0,66,NaN,1.0,89.79,1727.28,1,1.0,0.0,1.0,1
3,41.0,58,0.0,2.0,95.87,3930.67,1,1.0,1.0,0.0,0
4,6.0,22,1.0,1.0,21.78,143.25,3,0.0,0.0,1.0,1
5,45.0,53,0.0,2.0,23.49,1057.05,3,0.0,0.0,0.0,0
6,35.0,46,1.0,3.0,49.53,1726.09,2,1.0,0.0,0.0,0
7,7.0,40,1.0,1.0,82.67,624.40,1,1.0,0.0,1.0,1
8,21.0,52,0.0,2.0,47.06,988.26,2,0.0,1.0,1.0,3
9,21.0,42,0.0,1.0,90.45,1899.45,1,1.0,1.0,1.0,1
10,11.0,43,1.0,1.0,74.32,783.80,1,0.0,1.0,1.0,1
11,3.0,25,1.0,1.0,68.16,193.51,1,0.0,0.0,1.0,2
12,20.0,40,0.0,1.0,46.57,931.40,2,0.0,0.0,0.0,0
13,53.0,31,1.0,1.0,76.27,4033.81,1,0.0,1.0,0.0,0
14,32.0,45,0.0,1.0,87.01,2773.44,1,1.0,1.0,1.0,1
15,72.0,43,0.0,1.0,78.33,5632.88,1,0.0,0.0,1.0,4
16,36.0,51,1.0,2.0,80.40,2885.33,2,1.0,1.0,0.0,0
17,1.0,67,0.0,1.0,NaN,NaN,2,NaN,0.0,0.0,0
18,57.0,24,1.0,1.0,77.13,4391.92,2,1.0,1.0,0.0,0
19,17.0,43,1.0,1.0,18.00,321.60,3,0.0,0.0,0.0,0
20,7.0,25,1.0,2.0,102.22,728.78,1,1.0,1.0,1.0,2
21,4.0,41,1.0,1.0,49.70,179.02,2,0.0,0.0,0.0,0
22,6.0,18,0.0,3.0,NaN,NaN,1,0.0,1.0,1.0,1
23,53.0,24,0.0,3.0,72.15,3841.40,1,1.0,1.0,0.0,0
24,41.0,63,0.0,3.0,47.35,1943.89,2,0.0,0.0,0.0,0
25,15.0,42,1.0,1.0,73.90,1057.62,1,0.0,1.0,0.0,0
26,20.0,40,1.0,1.0,86.22,944.33,1,0.0,1.0,1.0,1
27,2.0,72,1.0,1.0,57.70,83.72,2,1.0,0.0,1.0,1
28,41.0,36,2.0,2.0,49.15,2015.15,2,1.0,1.0,0.0,0
29,20.0,44,0.0,1.0,66.95,1340.61,1,0.0,1.0,0.0,0
30,18.0,47,1.0,1.0,86.63,1555.51,1,1.0,0.0,1.0,2
31,22.0,18,1.0,1.0,57.87,1262.16,1,0.0,0.0,0.0,0
32,38.0,61,1.0,3.0,NaN,NaN,1,1.0,1.0,0.0,0
33,11.0,54,0.0,3.0,48.40,559.67,2,0.0,0.0,0.0,0
34,18.0,41,0.0,1.0,68.08,1241.93,2,1.0,1.0,1.0,1
35,46.0,38,0.0,2.0,60.92,2802.32,2,0.0,1.0,0.0,0
36,3.0,33,1.0,1.0,79.93,124.92,1,1.0,0.0,1.0,0
37,1.0,63,1.0,1.0,64.36,63.04,2,0.0,1.0,1.0,4
38,38.0,42,1.0,2.0,NaN,NaN,1,1.0,0.0,1.0,0
39,19.0,64,1.0,1.0,93.96,1808.75,1,1.0,1.0,1.0,1

In [130]:
churn_df.describe()

,Tenure_Months,Age,Gender,Contract_Type,Monthly_Charges,Total_Charges,Has_Multiple_Lines,Streaming_TV,Churn,Reason_for_Churn
count,10026.000000,10100.000000,9584.000000,10005.000000,9832.000000,9825.000000,10052.000000,10013.000000,10034.000000,10100.000000
mean,23.456713,42.167525,0.535058,1.662969,125.576805,2765.665162,0.457919,0.449016,0.358581,0.697921
std,18.227944,17.121377,0.519094,0.802182,799.529145,21393.542465,0.498251,0.497419,0.479608,1.193994
min,0.000000,-10.000000,0.000000,1.000000,-10.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,7.000000,32.000000,0.000000,1.000000,48.320000,361.220000,0.000000,0.000000,0.000000,0.000000
50%,21.000000,42.000000,1.000000,1.000000,64.630000,1050.640000,0.000000,0.000000,0.000000,0.000000
75%,36.000000,51.000000,1.000000,2.000000,77.290000,2201.970000,1.000000,1.000000,1.000000,1.000000
max,72.000000,150.000000,2.000000,3.000000,9999.000000,689929.370000,1.000000,1.000000,1.000000,4.000000